### ISSUE TITLE
Use google/fonts

### ISSUE THREAD

**Issue by davelab6** [FontsToRaisins/alexei-log#5]
I think we should not be using this org with individual repos. 

I think you should file an issue on https://github.com/google/fonts/issues with the contents of https://github.com/FontsToRaisins/alexei-log/blob/master/README.md and similarly file issue for anything 'collection level', and then file issues like https://github.com/FontsToRaisins/alexei-log/issues/3 in the individual project's issue tracker.

**Comment by alexeiva** [comment]
Alright. Now moved to https://github.com/google/fonts/issues/285
